version: "3.9"
services:
    clone:
        container_name: spotify-clone-container
        env_file: 
            -   .env.local
            -   .env.development.local
        build: "dockerfile.dev"
        volumes:
        -   .:/usr/src/app
        - ./node_modules:/usr/src/app/node_modules
        image: spotifyclone:latest
        ports: 
        -   '80:3000'